[기능추가] 방/일정 기능
CHZZK-Study/HOWMeet-Backend pull request #11
Opened 2024-08-09 17:45 UTC by SSUHYUNKIM

## 작업 내용
- 방 CRUD
- 일정 CRUD
- 방 멤버 관련 작업

## 테스트
### Service
![image](https://github.com/user-attachments/assets/6f13957b-f552-4e48-80b2-c0e98b4f63f0)

![image](https://github.com/user-attachments/assets/876a64a6-8cf1-42b1-ae55-cd0d5399bc68)

![image](https://github.com/user-attachments/assets/d8202b2a-141a-4ac7-ad93-af9e00775fd4)

### Controller
-  룸 생성
![image](https://github.com/user-attachments/assets/953bf2d4-d982-41b6-8f53-9f07c83bd99a)

- 룸 업데이트
![image](https://github.com/user-attachments/assets/44a404c1-957c-4ea5-9326-3f0f866fbfe1)

- 룸 멤버 업데이트
![image](https://github.com/user-attachments/assets/829e74f9-d8e0-4322-a7c5-a1fc2577229c)

- 룸 조회
![image](https://github.com/user-attachments/assets/9550a85e-e6f6-4198-8e79-7dd64a5d71b6)

- 룸 삭제
![image](https://github.com/user-attachments/assets/82a05841-95ef-4e3d-95bc-3194cc61eeb5)

- 룸 멤버 삭제
![image](https://github.com/user-attachments/assets/ca0b1173-dd33-4879-a5fa-9f5fdc55d110)

- 멤버 스케줄 생성
![image](https://github.com/user-attachments/assets/d698bce4-c850-4cb9-994a-aac3321f0eab)

- 멤버 스케줄 조회
![image](https://github.com/user-attachments/assets/a5669482-6abc-46b7-be2a-2df0ca403c20)

- 멤버 스케줄 삭제
![image](https://github.com/user-attachments/assets/3e79b295-2260-422c-9950-07c7a2aff0fe)

- 게스트 스케줄 생성
![image](https://github.com/user-attachments/assets/a63b6cd9-eb22-4191-9f76-365caa2f2008)

- 게스트 스케줄 조회
![image](https://github.com/user-attachments/assets/dd99a6cf-ab1a-443d-9342-b03157b8d6f4)

- 게스트 스케줄 삭제
![image](https://github.com/user-attachments/assets/cd243d08-c7b8-49f5-9441-fa0b13fcdd85)

## 기타 사항 (참고 자료, 문의 사항 등)
- 예외 처리는 새로운 브랜치에서 작업하겠습니다.
- OneToMany를 남발해둔 부분이 있어서 api 문서 생성 후 리팩토링으로 작업하겠습니다.
- 혹시 빠진 부분 있으면 알려주세요!

2024-08-12 07:45 UTC, kmw2378 reviewed
수고하셨습니다! 
추가로, 전체적으로 `final` 키워드가 누락된 것 같습니다! 이 부분도 수정해주시면 감사하겠습니다!

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/common/embedded/date/BaseDate.java
> +    }
통일성을 위해 `@Getter` 를 사용해도 괜찮을 것 같아요!

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/common/embedded/date/impl/ScheduleDate.java
> +public class ScheduleDate {
`BaseDate` 를 상속받지 않으니 패키지를 수정하는 건 어떨까요?

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/common/embedded/date/impl/ScheduleTime.java
> +    public static ScheduleTime of(LocalTime startTime, LocalTime endTime) {
파라미터에 `final` 키워드가 없습니다!

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/controller/RoomController.java
> +    @PatchMapping("/{roomId}/edit")
`Room` 에 대한 수정이라면 아래와 같이 URL에 `edit`을 붙일 필요는 없을 것 같아요!
```
PATCH /room/{roomId}
```

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomMemberResponse.java
> +    public static RoomMemberResponse of(final RoomMember roomMember) {
정적 팩토리 메서드 파라미터가 한 개인 경우는 메서드명이 `from` 입니다!

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/entity/Room.java
> +    }
setter는 아래와 같이 파라미터 검증이 있으면 좋을 것 같아요!

```suggestion
    public void updateName(final RoomName name) {
        if (!roomName.isNullOrEmpty()) {
            this.name = name;
        }
    }
```

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/entity/RoomMember.java
> +    @JsonIgnore
`@JsonIgnore` 을 붙이신 이유가 궁금합니다!

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
> +        Room room = new Room(roomRequest.description(), roomRequest.name());
`RoomRequest` 에 아래와 같은 메서드를 두는건 어떨까요?? 캡슐화가 더 지켜질 것 같습니다!

```java
public Room toEntity() {
    reutrn new Room(description, name);
}
```

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
> +        RoomMember leader = RoomMember.of(roomRequest.leaderMemberId(), savedRoom, true);
`RoomMember` 에서 방장을 만드는 메서드를 제공하는건 어떨까요?

```java
public class RoomMember {
    ...
    public static RoomMember createLeaderRoomMember(final memberId, final Room room) {
        return new RoomMember(...);
    }
}
```

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/dto/RoomRequest.java
> +        MemberSchedule memberSchedule,
계층간 의존성이 위배되는 것 같아요! (영속성 계층 - 표현 계층 의존) 별도 DTO를 만드는건 어떨까요?

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomService.java
> +    }
1. 방에 회원을 추가하는 메서드일까요? 메서드명이 애매한 것 같습니다!
2. 방 생성과 응답이 똑같은 이유가 궁금합니다!

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/schedule/controller/MSController.java
> +@RequestMapping("/member-schedule")
URL 을 카멜 케이스로 할지 하이픈으로 할지 논의를 해봐야될 것 같습니다!

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/schedule/controller/MSController.java
> +    }
생성 API의 경우 아래와 같이 상태 코드를 201, 헤더에 조회 URL 을 제공해주는건 어떨까요?

```suggestion
    @PostMapping
    public ResponseEntity<?> createMemberSchedule(@RequestBody final MSRequest msRequest) {
        final MSResponse msResponse = msService.createMemberSchedule(msRequest);
        returnreturn ResponseEntity.created(URI.create("/member-schedule/" + msResponse.id()))
                .body(msResponse);
        )
    }
```

2024-08-12 07:45 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/schedule/service/MSService.java
> +        String inviteLink = "http://localhost:8080/member-schedule/invite/" + memberSchedule.getId();
초대 링크를 만드는 클래스(`InviteUrlProvider`)를 따로 두는건 어떨까요?

2024-08-15 00:12 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/common/util/InviteUrlProvider.java
> +        this.baseUrl = "http://localhost:8080/" + basePath + "/invite/";
리터럴 문자열을 `yaml` 파일(`@Value`)이나 상수(`static final`)으로 관리하는 건 어떨까요?

2024-08-15 00:12 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Invalid room ID"));
이러한 코드는 재사용성을 위해 추출하는게 좋을 것 같아요!

2024-08-15 00:12 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberService.java
> +                .collect(Collectors.toList());
방에 속한 회원 수정 시 응답값이 방에 속한 회원인 이유가 궁금합니다!

2024-08-15 00:22 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/room/service/RoomMemberService.java
> +                .collect(Collectors.toList());
만약 수정 후 방에 속한 회원을 제공해야된다면 조회 API를 사용하게 하는게 더 REST Api 스러울 것 같아요!

2024-08-15 01:03 UTC, kmw2378 commented on src/main/java/org/chzzk/howmeet/domain/regular/schedule/service/MSService.java
> +        String inviteLink = inviteUrlProvider.generateInviteUrl("member-schedule", savedSchedule.getId());
InviteUrlProvider에 MemberSchedule 객체를 인수로 전달하면 캡슐화가 더 지켜질 것 같아요!

"member-schedule" 을 인수로 전달하는게 좀 아쉽네요ㅜㅜ getClass().getName() 을 사용하면 별도로 전달안해줘도 될 것 같은데... 캡슐화가 지켜지지 않는 느낌이네요ㅜ

별도 인터페이스를 만드는 방법도 있긴할 것 같지만 이러면 엔티티에서 View를 의존하게 되는 것 같아서 고민이네요ㅜ

이 부분은 같이 고민을 해봐야될 것 같아요!

2024-08-15 04:28 UTC, chech2 requested changes
수고하셨습니다!!

2024-08-15 04:28 UTC, chech2 commented on src/main/java/org/chzzk/howmeet/domain/regular/schedule/entity/MemberSchedule.java
memberSchedule은 ms가 아닌 memberSchedule로 사용하시는 걸까요??

2024-08-16 03:01 UTC, kmw2378 approved these changes

2024-08-16 03:03 UTC, chech2 approved these changes
확인했습니다! 수고하셨습니다!

2024-08-16 05:39 UTC, merged